"""fixed videocomments

Revision ID: 7b25fa5b4248
Revises: 85f50ffbcea5
Create Date: 2025-04-29 00:54:38.750740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b25fa5b4248'
down_revision: Union[str, None] = '85f50ffbcea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_comments', sa.Column('content', sa.String(), nullable=False))
    op.create_index(op.f('ix_video_comments_user_id'), 'video_comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_video_comments_video_id'), 'video_comments', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_comments_video_id'), table_name='video_comments')
    op.drop_index(op.f('ix_video_comments_user_id'), table_name='video_comments')
    op.drop_column('video_comments', 'content')
    # ### end Alembic commands ###
